AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: nodejs24.x
      Environment:
        Variables:
          # We are using the output of the shared resources CloudFormation template
          # that is passed down from Serverless Compose, and the staged param "domain".
          TABLE_NAME: ${param:tableName}
          DOMAIN: ${param:domain}
      Architectures:
        - arm64
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET

Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
