service: aws-python # NOTE: update this with your service name

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.14
  architecture: arm64

functions:
  hello:
    handler: handler.hello
