service: ${self:custom.serviceName}

frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64

  apiGateway:
    usagePlan:
      quota:
        limit: 100
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 100
        rateLimit: 50

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
          Resource: 'arn:aws:s3:::${self:custom.bucket}/*'
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
          Resource: 'arn:aws:s3:::${self:custom.bucket}/*'

custom:
  serviceName: image-resizing
  stage: ${opt:stage, self:custom.defaultStage}
  defaultBucket: image-resizing-${sls:stage}-${aws:accountId}
  bucket: ${env:BUCKET, self:custom.defaultBucket}
  defaultStage: dev

functions:
  resize:
    handler: src/handlers/resizer/index.handler
    events:
      - http:
          path: /{size}/{image}
          method: get
    environment:
      # Provide your bucket name here
      BUCKET: ${self:custom.bucket}
      REGION: us-east-1
