service: aws-node-rest-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
