service: aws-golang-simple-http-endpoint
frameworkVersion: '4'

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64

package:
  individually: true

functions:
  hello:
    handler: bootstrap
    package:
      artifact: bin/hello.zip
    events:
      - httpApi:
          path: /hello
          method: get
  world:
    handler: bootstrap
    package:
      artifact: bin/world.zip
    events:
      - httpApi:
          path: /world
          method: get
