service: text-analysis-sns

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: us-east-1
  stage: dev
  environment:
    SNS_TOPIC_ARN: arn:aws:sns:${aws:region}:${aws:accountId}:analyzeNote
  iam:
    role:
      statements:
        - Effect: Allow
          Resource: ${self:provider.environment.SNS_TOPIC_ARN}
          Action:
            - sns:Publish

functions:
  addNote:
    handler: addNote.addNote
    events:
      - http:
          path: notes
          method: post
          cors: true

  analyzeNote:
    handler: analyzeNote.analyzeNote
    events:
      - sns: analyzeNote
