service: aws-node-typescript-sqs-standard

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt: [ receiverQueue, Arn ]
      
functions:
  sender:
    handler: handler.sender
    events:
      - http:
          method: post
          path: sender

  receiver:
    handler: handler.receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn
resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: receiverQueue
