service: upload-to-s3-and-postprocess

frameworkVersion: '4'

custom:
  defaultBucket: upload-postprocess-${sls:stage}-${aws:accountId}
  bucket: ${env:BUCKET, self:custom.defaultBucket}

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"

functions:
  postprocess:
    handler: handler.postprocess
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
