service: aws-golang-s3-file-replicator
frameworkVersion: '4'

custom:
  defaultInputBucket: replicator-input-${aws:accountId}
  defaultOutputBucket: replicator-output-${aws:accountId}
  inputBucket: ${env:INPUT_BUCKET, self:custom.defaultInputBucket}
  outputBucket: ${env:OUTPUT_BUCKET, self:custom.defaultOutputBucket}

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  stage: dev
  region: ap-northeast-1
  memorySize: 128
  timeout: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:custom.outputBucket}/*"
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:custom.inputBucket}/*"

package:
  individually: true

functions:
  replicate:
    handler: bootstrap
    package:
      artifact: bin/replicate.zip
    environment:
      OUTPUT_BUCKET: ${self:custom.outputBucket}
    events:
      - s3:
          bucket: ${self:custom.inputBucket}
          existing: true
          event: s3:ObjectCreated:*
