service: aws-node-typescript-apollo-lambda

frameworkVersion: '4'

plugins:
  - serverless-offline

build:
  esbuild:
    configFile: ./esbuild.config.js

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  timeout: 15
  apiGateway:
    apiKeys:
      - name: lambdaApolloKey
        value: ${env:APOLLO_LAMBDA_KEY, 'your-api-key-that-is-at-least-characters-long'}

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          private: true
          path: graphql
          method: post
      - http:
          private: true
          path: graphql
          method: get
