service: hello-world

frameworkVersion: '4'

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  region: eu-west-1
  memorySize: 128

package:
  individually: true

functions:
  authorize:
    handler: bootstrap
    package:
      artifact: bin/authorize.zip
  authorize2:
    handler: bootstrap
    package:
      artifact: bin/authorize2.zip
  hello-world:
    handler: bootstrap
    package:
      artifact: bin/hello-world.zip
    events:
    - http:
        path: /hello
        method: get
    - http:
        path: /
        method: get
        authorizer:
          name: authorize
          resultTtlInSeconds: 0
  hello-world2:
    handler: bootstrap
    package:
      artifact: bin/hello-world2.zip
    events:
    - http:
        path: me
        method: get
        authorizer:
          name: authorize2
          resultTtlInSeconds: 0
