service: aws-node-ses-receive-email-body

frameworkVersion: '4'

custom:
  defaultBucket: ses-email-body-${sls:stage}-${aws:accountId}
  bucket: ${env:BUCKET, self:custom.defaultBucket}
  bucketRef: S3BucketSesemailbody${sls:stage}${aws:accountId}

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  postprocess:
    handler: handler.postprocess
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*

resources:
  Resources:
    S3EMailBucketPermissions:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: ${self:custom.bucketRef}
        PolicyDocument:
          Statement:
            - Principal:
                Service: "ses.amazonaws.com"
              Action:
                - s3:PutObject
              Effect: Allow
              Sid: "AllowSESPuts"
              Resource:
                Fn::Join: ['', ['arn:aws:s3:::', Ref: "${self:custom.bucketRef}", '/*'] ]
              Condition:
                StringEquals:
                  "aws:Referer": { Ref: AWS::AccountId }
