service: aws-rust-simple-http-endpoint
frameworkVersion: '4'

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  region: us-east-1 # make sure your region is correct

package:
  individually: true

functions:
  hello:
    handler: bootstrap
    package:
      artifact: bin/hello.zip
    events:
      - httpApi:
          path: /test/test
          method: get

