service: serverless-simple-http-endpoint
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get
