service: sqs-worker
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: sqs:SendMessage
          Resource: !GetAtt JobsQueue.Arn

functions:
  producer:
    handler: handler.producer
    environment:
      QUEUE_URL: !Ref JobsQueue
    events:
      - httpApi:
          path: /produce
          method: post
  consumer:
    handler: handler.consumer
    events:
      - sqs:
          arn: !GetAtt JobsQueue.Arn
          batchSize: 10

resources:
  Resources:
    JobsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-jobs-${sls:stage}
