service: aws-node-scheduled-cron

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: rate(1 minute)
