service: aws-ruby-line-bot

frameworkVersion: '4'

provider:
  name: aws
  runtime: ruby4.0
  architecture: arm64
  environment:
    LINE_CHANNEL_ACCESS_TOKEN: ${env:LINE_CHANNEL_ACCESS_TOKEN, 'YOUR_LINE_CHANNEL_ACCESS_TOKEN'}
    LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET, 'YOUR_LINE_CHANNEL_SECRET'}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post

plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - bundle config set --local deployment true
      - bundle install
