service: serverless-github-check

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: eu-west-1
  environment:
    GITHUB_TOKEN: ${ssm:githubToken, 'REPLACE-WITH-YOUR-GITHUB-TOKEN'}

functions:
  githubCheck:
    handler: handler.githubCheck
    events:
      - http:
          path: webhook
          method: post
          cors: true
