service: fetch-file-and-store-in-s3

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  stage: dev
  region: us-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: !Sub "${UploadBucket.Arn}/*"

functions:
  save:
    handler: handler.save
    environment:
      BUCKET: !Ref UploadBucket

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
