service: aws-node-stripe-integration

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  stage: test
  region: us-east-1
  environment:
    STRIPE_TEST_SECRET_KEY: sk_test_XXXXXXXXXXXXXXXXXXXXXXXX
    STRIPE_LIVE_SECRET_KEY: sk_live_XXXXXXXXXXXXXXXXXXXXXXXX

functions:
  incoming:
    handler: handler.incoming
    events:
      - http:
          path: stripe/incoming
          method: post
