service: aws-node-rest-api-typescript

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  environment:
    NODE_ENV: dev
    DB_URL: "${env:DB_URL, 'mongodb+srv://<user>:<password>@<your-cluster>.mongodb.net/test?retryWrites=true&w=majority'}"
    DB_NAME: ${env:DB_NAME, 'study'}
    DB_BOOKS_COLLECTION: ${env:DB_BOOKS_COLLECTION, 'books'}

plugins:
  - serverless-offline

package:
  patterns:
    - '!config/.env.stg'
    - '!config/.env.pro'

functions:
  create:
    handler: app/handler.create
    events:
      - http:
          path: books
          method: post
  update:
    handler: app/handler.update
    events:
      - http:
          path: books/{id}
          method: put
  find:
    handler: app/handler.find
    events:
      - http:
          path: books
          method: get
  findOne:
    handler: app/handler.findOne
    events:
      - http:
          path: books/{id}
          method: get

  deleteOne:
    handler: app/handler.deleteOne
    events:
      - http:
          path: books/{id}
          method: delete
