service: ruby-http-endpoint
frameworkVersion: '4'

provider:
  name: aws
  runtime: ruby4.0
  architecture: arm64

functions:
  current_time:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /time
          method: get
