service: aws-node-twilio

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  environment:
    # replace these env variables with your twilio account values
    TWILIO_ACCOUNT_SID: YOUR-TWILIO-ACCOUNT-SID-HERE
    TWILIO_AUTH_TOKEN: YOUR-TWILIO-AUTH-TOKEN-HERE
    TWILIO_PHONE_NUMBER: YOUR-TWILIO-PHONE-NUMBER-HERE

package:
  patterns:
    - '!*.test.js'
    - '!frontend/**'

functions:
  sendText:
    handler: handler.sendText
    events:
      - http:
          path: api/sendText
          method: post
          integration: lambda
          cors: true
