service: goservice # NOTE: update this with your service name

frameworkVersion: '4'

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64

package:
  individually: true

functions:
  get:
    handler: bootstrap
    package:
      artifact: bin/get.zip
    events:
      - http:
          path: get/{name}
          method: get
          request:
            parameters:
              paths:
                name: true
  getquery:
    handler: bootstrap
    package:
      artifact: bin/getquery.zip
    events:
      - http:
          path: getQ
          method: get
          request:
            parameters:
              querystrings:
                name: true
  post:
    handler: bootstrap
    package:
      artifact: bin/post.zip
    events:
      - http:
          path: post
          method: post
