service: hellotime-app

frameworkVersion: '4'

provider:
  name: aws
  architecture: arm64

functions:
  hello:
    runtime: python3.14
    events:
      - httpApi:
          method: get
          path: /greet
    handler: web/handler.hello
  time:
    runtime: nodejs24.x
    events:
      - httpApi:
          method: get
          path: /time
    handler: api/handler.timestamp
