app: aws-golang-rest-api-with-dynamodb
service: aws-golang-rest-api-with-dynamodb

frameworkVersion: '4'

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  individually: true

functions:
  create:
    handler: bootstrap
    package:
      artifact: bin/create.zip
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: bootstrap
    package:
      artifact: bin/list.zip
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: bootstrap
    package:
      artifact: bin/get.zip
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: bootstrap
    package:
      artifact: bin/update.zip
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: bootstrap
    package:
      artifact: bin/delete.zip
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
