service: gifmaker
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  mkgif:
    handler: handler.mkgif
    events:
      - s3: ${self:custom.bucket}
    layers:
      - {Ref: FfmpegLambdaLayer}

layers:
  ffmpeg:
    path: layer
    compatibleRuntimes:
      - nodejs24.x
    compatibleArchitectures:
      - arm64

custom:
  defaultBucket: gifmaker-${sls:stage}-${aws:accountId}
  bucket: ${env:BUCKET, self:custom.defaultBucket}
