service: gomapservice # NOTE: update this with your service name

frameworkVersion: '4'

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  environment:
    GOOGLE_API_KEY: AIzaXXXX #CHANGE YOUR API KEY
  region: ap-southeast-1

package:
  individually: true

functions:
  getgeolocation:
    handler: bootstrap
    package:
      artifact: bin/getgeolocation.zip
    events:
      - http:
          path: geolocation
          method: get
          request:
            parameters:
              querystrings:
                address: true
  getnearbylocation:
    handler: bootstrap
    package:
      artifact: bin/getnearbylocation.zip
    events:
      - http:
          path: nearbylocation
          method: get
          request:
            parameters:
              querystrings:
                location: true
                radius: true
                name: false
                type: false
  getgeodetail:
    handler: bootstrap
    package:
      artifact: bin/getgeodetail.zip
    events:
      - http:
          path: geodetail
          method: get
          request:
            parameters:
              querystrings:
                placeid: true
