plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.5.1'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    implementation 'com.amazonaws:aws-lambda-java-core:1.4.0'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.22.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.22'
}

// http://docs.aws.amazon.com/lambda/latest/dg/create-deployment-pkg-zip-java.html
shadowJar {
    archiveBaseName.set('aws-java-simple-http-endpoint')
    archiveClassifier.set('')
    archiveVersion.set('')
}

build.dependsOn shadowJar
