service: aws-java-simple-http-endpoint
frameworkVersion: '4'

provider:
  name: aws
  runtime: java25
  architecture: arm64

package:
  artifact: build/libs/aws-java-simple-http-endpoint.jar

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /time
          method: get
