service: serverless-http-api-typescript
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
