service: replicator

frameworkVersion: '4'

plugins:
  - serverless-lift

constructs:
  inputBucket:
    type: storage
  outputBucket:
    type: storage

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  stage: dev
  region: us-east-1

functions:
  replicate:
    handler: handler.replicate
    environment:
      OUTPUT_BUCKET: ${construct:outputBucket.bucketName}
    events:
      - s3:
          bucket: ${construct:inputBucket.bucketName}
          existing: true
